config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'index#index'
  resources :students, :teamleads, :teachers, :teams, :groups, :schools
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  validates :name, length: { minimum: 3, maximum: 128 }, uniqueness: true
  has_many :students, dependent: :nullify
  belongs_to :teacher, optional: true
end

# == Schema Information
#
# Table name: groups
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  teacher_id :bigint(8)
#
# Indexes
#
#  index_groups_on_teacher_id  (teacher_id)
#

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :load_group, only: %i[show edit update destroy]

  def index
    @q = Group.ransack(search_params)
    @groups = @q.result.order(:name).page(params[:page])
    @teachers = Teacher.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  private

  def load_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :teacher_id)
  end

  def search_params
    params[:q]&.permit(%w[name_cont teacher_id_eq])
  end
end

app/views/groups/_form.html.slim
.column.is-one-third
  = render partial: 'shared/errors', locals: {model: @group}
  = simple_form_for(@group) do |f|
    = f.input :name
    = f.label 'Teacher', class: 'label'
    = f.association :teacher, label: false
    .field.is-grouped  
      .control
        = f.button :submit, class: 'is-primary'
      .control
        = link_to 'Back', @group, class: 'button is-text'

app/views/groups/_group_item.html.slim
tr
  td 
    = group.id
    = link_to '', group, method: :delete, class: 'delete cell-inner-button', data: {confirm: 'Are you sure?'}
  td = link_to group.name, group
  td = group.teacher.nil? ? '-' : link_to(group.teacher.name, group.teacher)

app/views/groups/_search_form.html.slim
.block.has-background-success.search-form
  = search_form_for @q do |f|
    .columns.is-desktop
      .column
        .field
          = f.label :name_cont, class: :label
          = f.search_field :name_cont, class: :input
      .column
        .field
          = f.label :teacher_id_eq, class: :label
          .select
            = f.collection_select :teacher_id_eq, @teachers, "id", "name", {prompt: 'Select teacher'}
      
      .buttons style="padding: 1rem;"
          = link_to 'Clear', groups_path, class: 'button is-danger'
          = f.submit 'Search', class: 'button is-link'
      

app/views/groups/edit.html.slim
.title.has-text-info Edit Group
= render 'form'

app/views/groups/index.html.slim
= render partial: 'shared/index_header', locals: {header: 'Groups', path: new_group_path}
= render 'search_form'
= paginate @groups
table.table.is-bordered.is-hoverable.is-striped.is-fullwidth
  thead
    tr
      th #
      th Name
      th Teacher
  tbody
    = render partial: 'group_item', collection: @groups, as: :group

app/views/groups/new.html.slim
.title.has-text-info New Group
= render 'form'

app/views/groups/show.html.slim
.column.is-one-third
  .card
    header.card-header.has-background-light
      p.card-header-title.title.has-text-info Group
    .card-content
      table.table
        tbody
          tr
            td Name: 
            td.subtitle = @group.name
          tr
            td Teacher:
            td = @group.teacher.nil? ? '-' : link_to(@group.teacher.name, @group.teacher)



    footer.card-footer
      = link_to 'Edit', edit_group_path(@group.id), class: 'card-footer-item '
      = link_to 'Delete', group_path(@group.id), method: :delete, class: 'card-footer-item', data: {confirm: 'Are you sure?'}
      = link_to 'Show all', groups_path, class: 'card-footer-item'