config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'index#index'
  resources :students, :teamleads, :teachers, :teams, :groups, :schools
end

app/views/shared/_errors.html.slim
- model.errors.full_messages.each do |message|
  .notification.is-warning
    = message

app/views/shared/_flashes.html.slim
- flash.each do |key, message|
  .notification.is-info = message

app/views/shared/_index_header.html.slim
.card
  .card-content.has-background-success
    .level
      .title.is-1.has-text-light = header
      div
        a.button.is-large.is-success href="#{path}"
            span.icon
              i.fas.fa-plus-circle
            span Add
      

app/views/shared/_navigation.html.slim
nav.navbar.has-background-black-ter.is-fixed-top aria-label=("main navigation") role="navigation" 
  .navbar-menu
    .navbar-start 
      = link_to 'Home', root_path, class: 'navbar-item'
      .navbar-item.has-dropdown.is-hoverable
        a.navbar-link Users
        .navbar-dropdown
          = link_to 'Students', students_path, class: 'navbar-item'
          = link_to 'Teamleads', teamleads_path, class: 'navbar-item'
          = link_to 'Teachers', teachers_path, class: 'navbar-item'
      = link_to 'Teams', teams_path, class: 'navbar-item'
      = link_to 'Groups', groups_path, class: 'navbar-item'
      = link_to 'Schools', schools_path, class: 'navbar-item'
    .navbar-end
      .navbar-item
          - if user_signed_in?
            .buttons
              a.button.is-primary
                span.icon
                  i class="fas fa-#{get_icon(current_user)}"
                = current_user.name
              = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'button is-info'

              

app/views/shared/_user_form.html.slim
.column.is-one-third
  = render partial: 'shared/errors', locals: {model: user}
  = simple_form_for(user) do |f|
    = f.input :name
    = f.input :email
    = f.input :msisdn
    .field.is-grouped  
      .control
        = f.button :submit, class: 'is-primary'
      .control
        = link_to 'Back to profile', user, class: 'button is-text'

app/views/shared/_user_item.html.slim
tr
  td 
    = user.id
    = link_to '', user, method: :delete, class: 'delete cell-inner-button', data: {confirm: 'Are you sure?'}
  td
    = link_to user.name, user
  td = user.email
  td = user.msisdn