config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'index#index'
  resources :students, :teamleads, :teachers, :teams, :groups, :schools
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < User
  has_many :groups, dependent: :nullify
  belongs_to :school, optional: true
end

# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string           not null
#  encrypted_password     :string           default(""), not null
#  msisdn                 :string
#  name                   :string           not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  type                   :string           not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  group_id               :bigint(8)
#  school_id              :bigint(8)
#  team_id                :bigint(8)
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_group_id              (group_id)
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_school_id             (school_id)
#  index_users_on_team_id               (team_id)
#

app/controllers/teachers_controller.rb
# frozen_string_literal: true

class TeachersController < ApplicationController
  before_action :load_teacher, only: %i[show edit update destroy]

  def index
    @q = Teacher.ransack(search_params)
    @teachers = @q.result.order(:name).page(params[:page])
    @schools = School.all
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      redirect_to @teacher, notice: 'Teacher was successfully created.'
    else
      render :new
    end
  end

  def update
    if @teacher.update(teacher_params)
      redirect_to @teacher, notice: 'Teacher was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @teacher.destroy
    redirect_to teachers_path, notice: 'Teacher was successfully deleted.'
  end

  private

  def load_teacher
    @teacher = Teacher.find(params[:id])
  end

  def teacher_params
    params.require(:teacher).permit(:name, :email, :msisdn, :school_id, :password)
  end

  def search_params
    params[:q]&.permit(%w[name_cont email_cont msisdn_cont school_id_eq])
  end
end

app/views/teachers/_form.html.slim
.column.is-one-third
  = render partial: 'shared/errors', locals: {model: @teacher}
  = simple_form_for(@teacher) do |f|
    = f.input :name
    = f.input :email
    = f.input :msisdn
    = f.label 'School', class: 'label'
    = f.association :school, label: false
    .field.is-grouped  
      .control
        = f.button :submit, class: 'is-primary'
      .control
        = link_to 'Back to profile', @teacher, class: 'button is-text'

app/views/teachers/_search_form.html.slim
.block.has-background-success.search-form
  = search_form_for @q do |f|
    .columns.is-desktop
      .column
        .field
          = f.label :name_cont, class: :label
          = f.search_field :name_cont, class: :input
      .column
        .field
          = f.label :email_cont, class: :label
          = f.search_field :email_cont, class: :input
      .column
        .field
          = f.label :msisdn_cont, class: :label
          = f.search_field :msisdn_cont, class: :input
      .column
        .field
          = f.label :school_id_eq, class: :label
          .select
            = f.collection_select :school_id_eq, @schools, "id", "name", {prompt: 'Select school'}
      
      .buttons style="padding: 1rem;"
          = link_to 'Clear', teachers_path, class: 'button is-danger'
          = f.submit 'Search', class: 'button is-link'
      

app/views/teachers/_teacher_item.html.slim
tr
  td 
    = teacher.id
    = link_to '', teacher, method: :delete, class: 'delete cell-inner-button', data: {confirm: 'Are you sure?'}
  td
    = link_to teacher.name, teacher
  td = mail_to teacher.email
  td = teacher.msisdn
  td = teacher.school.nil? ? '-' : link_to(teacher.school.name, teacher.school)

app/views/teachers/edit.html.slim
.title.has-text-info Edit Teacher
=render 'form'

app/views/teachers/index.html.slim
= render partial: 'shared/index_header', locals: {header: 'Teacher', path: new_teacher_path}
= render 'search_form'
= paginate @teachers
table.table.is-bordered.is-hoverable.is-striped.is-fullwidth
  thead
    tr
      th #
      th Name
      th Email
      th Phone
      th School
  tbody
  = render partial: 'teacher_item', collection: @teachers, as: :teacher

app/views/teachers/new.html.slim
.title.has-text-info New Teacher
= render 'form'

app/views/teachers/show.html.slim
.column.is-one-third
  .card
    header.card-header.has-background-light
      p.card-header-title.title.has-text-info Teacher
    .card-content
      table.table
        tbody
          tr
            td Name: 
            td.subtitle = @teacher.name
          tr
            td Email:
            td = mail_to @teacher.email
              
          tr
            td Phone:
            td = @teacher.msisdn
          tr
            td School:
            td = @teacher.school.nil? ? '-' : link_to(@teacher.school.name, @teacher.school)



    footer.card-footer
      = link_to 'Edit', edit_teacher_path(@teacher.id), class: 'card-footer-item '
      = link_to 'Delete', teacher_path(@teacher.id), method: :delete, class: 'card-footer-item', data: {confirm: 'Are you sure?'}
      = link_to 'Show all', teachers_path, class: 'card-footer-item'