config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'index#index'
  resources :students, :teamleads, :teachers, :teams, :groups, :schools
end

app/models/school.rb
# frozen_string_literal: true

class School < ApplicationRecord
  validates :name, presence: true, length: { minimum: 1, maximum: 128 }
  validates :address, presence: true, length: { minimum: 2, maximum: 128 }
  has_many :teachers, dependent: :nullify
end

# == Schema Information
#
# Table name: schools
#
#  id         :bigint(8)        not null, primary key
#  address    :string
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/schools_controller.rb
# frozen_string_literal: true

class SchoolsController < ApplicationController
  before_action :load_school, only: %i[show edit update destroy]

  def index
    @q = School.ransack(search_params)
    @schools = @q.result.order(:name).page(params[:page])
    @teachers = Teacher.all
  end

  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)

    if @school.save
      redirect_to @school, notice: 'School was successfully created.'
    else
      render :new
    end
  end

  def update
    if @school.update(school_params)
      redirect_to @school, notice: 'School was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @school.destroy
    redirect_to schools_url, notice: 'School was successfully destroyed.'
  end

  private

  def load_school
    @school = School.find(params[:id])
  end

  def school_params
    params.require(:school).permit(:name, :address)
  end

  def search_params
    params[:q]&.permit(%w[name_cont address_cont teachers_id_eq])
  end
end

app/views/schools/_form.html.slim
.column.is-one-third
  = render partial: 'shared/errors', locals: {model: @school}
  = simple_form_for(@school) do |f|
    = f.input :name
    = f.input :address
    .field.is-grouped  
      .control
        = f.button :submit, class: 'is-primary'
      .control
        = link_to 'Back', @school, class: 'button is-text'

app/views/schools/_school_item.html.slim
tr
  td 
    = school.id
    = link_to '', school, method: :delete, class: 'delete cell-inner-button', data: {confirm: 'Are you sure?'}  
  td = link_to school.name, school
  td = school.address

app/views/schools/_search_form.html.slim
.block.has-background-success.search-form
  = search_form_for @q do |f|
    .columns.is-desktop
      .column
        .field
          = f.label :name_cont, class: :label
          = f.search_field :name_cont, class: :input
      .column
        .field
          = f.label :address_cont, class: :label
          = f.search_field :address_cont, class: :input
      
      .buttons style="padding: 1rem;"
          = link_to 'Clear', schools_path, class: 'button is-danger'
          = f.submit 'Search', class: 'button is-link'
      

app/views/schools/edit.html.slim
.title.has-text-info Edit School
= render 'form'

app/views/schools/index.html.slim
= render partial: 'shared/index_header', locals: {header: 'Schools', path: new_school_path}
= render 'search_form' 
= paginate @schools
table.table.is-bordered.is-hoverable.is-striped.is-fullwidth
  thead
    tr
      th #
      th Name
      th Address
  tbody
    = render partial: 'school_item', collection: @schools, as: :school

app/views/schools/new.html.slim
.title.has-text-info New School
= render 'form'

app/views/schools/show.html.slim
.column.is-one-third
  .card
    header.card-header.has-background-light
      p.card-header-title.title.has-text-info School
    .card-content
      table.table
        tbody
          tr
            td Name: 
            td.subtitle = @school.name
          tr
            td Address: 
            td.subtitle = @school.address
          

    footer.card-footer
      = link_to 'Edit', edit_school_path(@school.id), class: 'card-footer-item '
      = link_to 'Delete', school_path(@school.id), method: :delete, class: 'card-footer-item', data: {confirm: 'Are you sure?'}
      = link_to 'Show all', schools_path, class: 'card-footer-item'